### ISSUE TITLE
Consistently getting error when trying to import Brainscape cards

### ISSUE THREAD

**Issue by Rwaltzwills** [Pinkk-Flag/Brainscape-To-Anki#3]
Error is as follows. Attempted to import the example deck from add-on description, https://www.brainscape.com/flashcards/topic-8-particle-nuclear-7466676/packs/9913339 

```
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.26100

Traceback (most recent call last):
  File "anki.notes", line 154, in _field_index
KeyError: 'Front'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rwalt\AppData\Roaming\Anki2\addons21\403833522\__init__.py", line 96, in fetch_and_create_deck
    note["Front"] = card_text[i]
  File "anki.notes", line 162, in __setitem__
  File "anki.notes", line 156, in _field_index
KeyError: 'Front'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AnkiConnect ['2055492159', 2024-11-07T10:34, 'None', mod]
Auto Sync ['501542723', 2023-11-21T01:14, 'None', '']
Brainscape Flashcards to Anki ['403833522', 2024-10-23T10:28, 'None', '']
JapaneseFurigana ['678316993', 2024-08-06T00:46, 'None', mod]
Kanji Grid Kuuube ['1610304449', 2024-11-20T12:11, 'None', '']
export cardsnotes from browser with metadata to csv or xlsx ['1967530655', 2024-03-28T22:16, 'None', '']

===IDs of active AnkiWeb add-ons===
1610304449 1967530655 2055492159 403833522 501542723 678316993

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

```

**Comment by Pinkk-Flag** [comment]
Hello! Thank you for reporting this.

It has honestly been quite a frequent bug that I've seen.

What has worked for most people is to this:

1. Open Anki
2. To the `tools` section (at the top).
3. Click on `manage note types`
4. Then add the 'front' card type or whatever it is that is missing. From your case I believe it's the 'front' card type.
5. Restart anki and try importing again

This is what mostly fixes many issues that people have with this. If the error is still there, reply again :)

**Comment by Rwaltzwills** [comment]
@Pinkk-Flag - Thank you, this worked!

**Comment by Pinkk-Flag** [comment]
Hi @Rwaltzwills , you're welcome! And thank you for using my add-on :)
